# consup_baseos
# CONSUP base OS image for default (64bit) platform
# See https://github.com/LeKovr/consup
#

FROM debian:jessie

MAINTAINER Alexey Kovrizhkin <lekovr+docker@gmail.com>

ENV CONSUP_UBUNTU_CODENAME jessie

