# consup_baseos
# CONSUP base os image for 32bit platform
# https://github.com/LeKovr/consup/tree/master/Dockerfiles/baseos

# Ubuntu 12.04 LTS
#FROM octoblu/ubuntu-12.04-32bit-node

# Ubuntu 14.04 LTS
#FROM i686/ubuntu

# Debian Wheezy
FROM protomouse/debian-i386:wheezy

MAINTAINER Alexey Kovrizhkin <lekovr+docker@gmail.com>

# Save arch for childs
ENV DOCKER_ARCH 386
